### ISSUE TITLE
UnexpectedValueException: Hook handlers can only return null or a boolean.

### ISSUE THREAD

**Issue by avidseeker** [aaronpk/indielogin.com#123]
Trying to log in to IndieWeb wiki:

```
MediaWiki internal error.

Original exception: [0f8e3429935ecd4235ccaded] /wiki/index.php?title=Main_Page UnexpectedValueException: Hook handlers can only return null or a boolean. Got an unexpected value from handler *closure#00000000000000130000000000000000* for AuthRemoteuserFilterUserName
Backtrace:
from /web/sites/indieweb.org/public/wiki/includes/HookContainer/HookContainer.php(172)
#0 /web/sites/indieweb.org/public/wiki/includes/Hooks.php(132): MediaWiki\HookContainer\HookContainer->run()
#1 /web/sites/indieweb.org/public/wiki/extensions/Auth_remoteuser/src/UserNameSessionProvider.php(289): Hooks::run()
#2 /web/sites/indieweb.org/public/wiki/includes/session/SessionManager.php(537): MediaWiki\Extension\Auth_remoteuser\UserNameSessionProvider->provideSessionInfo()
#3 /web/sites/indieweb.org/public/wiki/includes/session/SessionManager.php(244): MediaWiki\Session\SessionManager->getSessionInfoForRequest()
#4 /web/sites/indieweb.org/public/wiki/includes/Request/WebRequest.php(840): MediaWiki\Session\SessionManager->getSessionForRequest()
#5 /web/sites/indieweb.org/public/wiki/includes/session/SessionManager.php(165): MediaWiki\Request\WebRequest->getSession()
#6 /web/sites/indieweb.org/public/wiki/includes/Setup.php(486): MediaWiki\Session\SessionManager::getGlobalSession()
#7 /web/sites/indieweb.org/public/wiki/includes/WebStart.php(92): require_once(string)
#8 /web/sites/indieweb.org/public/wiki/index.php(44): require(string)
#9 {main}

Exception caught inside exception handler: [0f8e3429935ecd4235ccaded] /wiki/index.php?title=Main_Page UnexpectedValueException: Hook handlers can only return null or a boolean. Got an unexpected value from handler *closure#00000000000000130000000000000000* for AuthRemoteuserFilterUserName
Backtrace:
from /web/sites/indieweb.org/public/wiki/includes/HookContainer/HookContainer.php(172)
#0 /web/sites/indieweb.org/public/wiki/includes/Hooks.php(132): MediaWiki\HookContainer\HookContainer->run()
#1 /web/sites/indieweb.org/public/wiki/extensions/Auth_remoteuser/src/UserNameSessionProvider.php(289): Hooks::run()
#2 /web/sites/indieweb.org/public/wiki/includes/session/SessionManager.php(537): MediaWiki\Extension\Auth_remoteuser\UserNameSessionProvider->provideSessionInfo()
#3 /web/sites/indieweb.org/public/wiki/includes/session/SessionManager.php(244): MediaWiki\Session\SessionManager->getSessionInfoForRequest()
#4 /web/sites/indieweb.org/public/wiki/includes/Request/WebRequest.php(840): MediaWiki\Session\SessionManager->getSessionForRequest()
#5 /web/sites/indieweb.org/public/wiki/includes/user/User.php(1024): MediaWiki\Request\WebRequest->getSession()
#6 /web/sites/indieweb.org/public/wiki/includes/user/User.php(393): MediaWiki\User\User->loadDefaults()
#7 /web/sites/indieweb.org/public/wiki/includes/user/User.php(1637): MediaWiki\User\User->load()
#8 /web/sites/indieweb.org/public/wiki/includes/user/User.php(2297): MediaWiki\User\User->getId()
#9 /web/sites/indieweb.org/public/wiki/includes/user/UserOptionsManager.php(656): MediaWiki\User\User->isRegistered()
#10 /web/sites/indieweb.org/public/wiki/includes/user/UserOptionsManager.php(500): MediaWiki\User\UserOptionsManager->getCacheKey()
#11 /web/sites/indieweb.org/public/wiki/includes/user/UserOptionsManager.php(147): MediaWiki\User\UserOptionsManager->loadUserOptions()
#12 /web/sites/indieweb.org/public/wiki/includes/context/RequestContext.php(459): MediaWiki\User\UserOptionsManager->getOption()
#13 /web/sites/indieweb.org/public/wiki/includes/language/Message.php(389): RequestContext->getLanguage()
#14 /web/sites/indieweb.org/public/wiki/includes/language/Message.php(1485): Message->getLanguage()
#15 /web/sites/indieweb.org/public/wiki/includes/language/Message.php(972): Message->fetchMessage()
#16 /web/sites/indieweb.org/public/wiki/includes/language/Message.php(1059): Message->format()
#17 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionRenderer.php(254): Message->text()
#18 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionRenderer.php(191): MWExceptionRenderer::msg()
#19 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionRenderer.php(105): MWExceptionRenderer::reportHTML()
#20 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionHandler.php(134): MWExceptionRenderer::output()
#21 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionHandler.php(251): MWExceptionHandler::report()
#22 /web/sites/indieweb.org/public/wiki/includes/exception/MWExceptionHandler.php(219): MWExceptionHandler::handleException()
#23 [internal function]: MWExceptionHandler::handleUncaughtException()
#24 {main}
```

**Comment by aaronpk** [comment]
This appears to be a problem with the indieweb wiki, not this website.
